#!/usr/bin/bash

### script to initialize a LaTeX document ###

## TODO:
## - choose the LaTeX compilation type (pdflatex, latex) and the output
##  file type (pdf, ps, dvi), and modify the latexmkrc and ultipack (options
##  for graphicx, hyperref and cleveref) files accordingly

## FLAG TO COPY THE TEMPLATE FOR A LATEX DOCUMENT INTO THE PARENT DIRECTORY ##
MAINFLG=0

## DESIRED NAME FOR THE LATEX DOCUMENT (without extension) ##
NAME="document"

##########

# get the name of the current directory
DIR=$(echo "${PWD##*/}")

# create relative symlinks for the gitignore and latexmkrc files
# into the parent directory
ln -s $DIR/latexmkrc ../.latexmkrc
ln -s $DIR/gitignore ../.gitignore

# only copy the template document if requested
if [ $MAINFLG -eq 1 ]; then

    # find and replace current directory name in main.tex (input commands)
    sed -i s/input{latex/input{$DIR/g main.tex

    # move and rename the template document file into the parent directory
    mv main.tex ../$NAME.tex
fi

